import { User } from "../../src/app/core/stores/user/user.store";
import { faker } from "@faker-js/faker";

export const defaultUser: User = {
  Id: 1,
  FirstName: "John",
  LastName: "Doe",
  NavTab: "Modules",
  NumberOfTemplates: 100,
  Pin: "1234",
  Token: "ABCD1234",
  TemplatesLastUpdate: new Date(),
  Url: "",
  Site: { Id: 1, Name: "Site Somewhere" },
  SelectedSite: { Id: 1, Name: "Site Somewhere" },
  UseFingerReader: true,
  UserSites: [],
  UserCompanies: [],
  ShowWeightingsOnApp: true,
  CompanyName: faker.company.name(),
  CanAddAsssetsToDocsByName: true,
  CanAddOperativesToDocsByName: true,
  CanAddQRsToAssets: true,
  CanModifyOperativeQRs: true,
  CanOffHireAssets: true,
  CanViewOtherOperativeInfo: true,
  Colour: faker.color.rgb({ prefix: "" }),
  CompanyId: 1,
  DocumentListingTab: "Recent",
  DownloadedTemplates: 100, 
  FontColour: faker.color.rgb({ prefix: "" }),
  HasAssetCreation: true,
  HasAssets: true,
  HasBasicOpInfo: true,
  HasCategoryActioners: true,
  HasCollabPlanning: true,
  HasCompanies: true,
  HasCompanySelectWithOtherOption: true,
  HasCustomLookups: true,
  HasDataTouchAreas: true,
  HasDocDrop: true,
  HasDocQrCodes: true,
  HasDocQueues: true,
  HasHadWifiPreferenceChecked: true,
  HasHideOperativeScan: true,
  HasLiveQueues: true,
  HasMyOpInfo: true,
  HasOperativeInfo: true,
  HasPlanningMeeting: true,
  HasProjectsOnDocDrop: true,
  HasQueueSupervisors: true,
  HasRamsList: true,
  HasRandomOperativebarcodes: true,
  HasRegisteredPlayerId: 1,
  HasResAreas: true,
  HasReviewMeeting: true,
  HasShowParentAnswersOnChildDoc: true,
  HasSimpleSwipes: true,
  HasSites: true,
  HasTemplateSender: true,
  HasUpdateableDocs: true,
  HasViewDocumentAsSinglePage: true,
  HideSearchOnOperativeAccess: true,
  HideSearchOnOperativeInfo: true,
  IsInSupervisorRole: true
}